# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Rong Liu
title: Master Student in Artificial Intelligence
affiliation: University of Southern California
email: rliu8691@usc.edu
# email_title: Email (Email title override)
phone: (213)519-8268
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  RongLiu-Leo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: rong-liu-34a3b4251
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
googlescholar_username: MrWUyWkAAAAJ





# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Interested in Computer Vision and Deep Learning

  Expecting the potential of AI & Art

  Looking for research opportunities 


content:

  - title: Publication
    layout: image
    content:
      - title: 'UAV swarm based radar signal sorting via multi-source data fusion: A deep transfer learning framework'
        image: images/UAV.jpg
        caption: Liangtian Wan, Rong Liu, Lu Sun, Hansong Nie, Xianpeng Wang
        description: |
          Information Fusion. 78 (2022): 90-101

          [Paper](https://www.sciencedirect.com/science/article/pii/S1566253521001834) | 
          [Patent](https://patentscope.wipo.int/search/en/detail.jsf?docPN=CN113030958)


  - title: Project # Title for the section
    layout: image # Type of content section (list/text)
    content:
      - title: Store Sales - Time Series Forecasting
        image: images/comparison.png
        description: | # this will include new lines to allow paragraphs
          The fundamental goal of this project is to forecast sales for a company in Ecuador, Corporación Favorita, using time series data, which covers 54 stores with 33 product families, spanning from 2013-01-01 to 2017-08-15. 
          To achieve this goal, the project employs Darts to process the data and perform exploratory data analysis. 
          After setting the Exponential Smoothing baseline model and boosting it using ensemble methods, the LightGBM algorithm showed the best performance. 
          Additionally, the project used model stacking, quadratic fitting, and genetic mutation algorithm to further optimize the forecast, resulting in a top 5 ranking on the leaderboard.
          
          [Kaggle Competition](https://www.kaggle.com/competitions/store-sales-time-series-forecasting) |
          [Report](https://drive.google.com/file/d/1qFx3XvNh6RqaNpol3grpwS9sHMt-dqp4/view?usp=share_link)

      - title: Video Style Transfer
        image: images/video_style_transfer/output2.gif

        description: | 
          This is a CSCI 590 Directed Research project supervised by Prof. [Scott Easley](https://viterbi.usc.edu/directory/faculty/Easley/Scott), 
          which aims to build a pipeline with new cost-effective and professional-looking cinematic imagery that transfers styles of the given image into a video.
          
          [Code](https://github.com/RongLiu-Leo/Video-Style-Transfer)

  - title: Experience
    layout: list
    content:
      - title: Teaching assistant
        sub_title: Dalian University of Technology
        caption: September 2021-June 2022
        description: |
          During my undergraduate studies at Dalian University of Technology, I had the opportunity to serve as a teaching assistant for two courses: 1. Program Design Basics and C Programming 2. Object-Oriented Method and C++ Program Design. In this role, I was responsible for holding office hours to assist students with their questions, as well as grading assignments and exams. These experiences allowed me to gain valuable TA experience. 

      - title: Cousera
        sub_title: Certification
        description: |
          - [Machine Learning](https://coursera.org/share/8197719d9771604ff45a12ea0ab80f4f)
          - [Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization](https://coursera.org/share/c9631e34c978f9ccf608c1588220827a)
          - [Neural Networks and Deep Learning](https://coursera.org/share/745ad08dcb8450f85de6637dd72d970b)

  
  
  - title: When I take a break from AI
    layout: text
    content: | # this will include new lines to allow paragraphs
      Play LOL, TFT, and cat.





sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
