# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Rong Liu
title: Master Student in Computer Science (AI) 
affiliation: University of Southern California
email: rliu8691@usc.edu
# email_title: Email (Email title override)
phone: (213)519-8268
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  RongLiu-Leo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: rong-liu-34a3b4251
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0003-3914-6704
googlescholar_username: MrWUyWkAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.



content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Dalian University of Technology
        sub_title: Bachelor of Engineering in Cyber Engineering
        caption: 2018 - 2022
        seal: images/DLUT.png


        description: | # this will include new lines to allow paragraphs
          **GPA: 88/100**

          Selected Courses:

          - Program Design Basics and C Programming
          - Object-Oriented Method and C++ Program Design
          - Computer Organization and Structure 
          - Data Structures and Algorithms
          - Database
          - Software Engineering
          - Operating System
          - Computer Network
          - Artificial Intelligence
      - layout: left
        title: University of Southern California
        sub_title: Master of Science in Computer Science (<a href="https://www.cs.usc.edu/academic-programs/masters/artificial-intelligence/">AI</a>)
        caption: 2022 - present
        seal: images/USC.png

          
        description: | # this will include new lines to allow paragraphs
          **GPA: 4.0/4.0**

          Courses:
          - [CSCI 561 Foundations of AI](https://drive.google.com/file/d/1xQ9tMWfQO7vQyQjUaxkMetBQNxXPGAaY/view?usp=share_link):

          Experienced on Genetic Algorithm, Min-Max and Reinforcement Learning, and Neural Network.
          - [CSCI 567 Machine Learning](https://vatsalsharan.github.io/fall22.html):

          Experienced on Perceptron, SVM, Nerual Network, SVM, Decision Trees, Ensemble Methods, Clustering, PCA, and Kaggle competition (Final report).
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*



# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
